trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: $(node_version)
    displayName: 'Setup Node.js'

  - checkout: self

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm test
    displayName: 'Run Tests'
