trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

# pool:
#   vmImage: 'ubuntu-latest'
pool:
  name: Default  # Change this to match your agent pool name


jobs:
- job: BuildAndTest
  timeoutInMinutes: 30  # Ensures job doesn't run indefinitely
  steps:
    - checkout: self

    - task: UseNode@1
      inputs:
        version: 16  # Specify a default Node.js version
      displayName: 'Setup Node.js'

    - script: npm install
      displayName: 'Install Dependencies'

    - script: npm test
      displayName: 'Run Tests'
