trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet build --configuration Release
      displayName: 'Build Application'

    - script: dotnet test --configuration Release
      displayName: 'Run Tests'

- stage: Deploy
  jobs:
  - deployment: DeployWebApp
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure Service Connection'
              appName: 'my-web-app'
              package: '$(System.DefaultWorkingDirectory)/build_output.zip'
