version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Create Artifacts"
          command: |
            echo "This is an artifact" > /tmp/artifact.txt
      - store_artifacts:
          path: /tmp/artifact.txt

workflows:
  say-hello-workflow:
    jobs:
      - say-hello