name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm run test:coverage
    
    - name: Generate XML test reports
      run: npm run test:xml
    
    - name: Create test reports zip
      run: |
        mkdir -p test-artifacts
        cp -r test-results/* test-artifacts/ 2>/dev/null || true
        cp -r coverage/* test-artifacts/ 2>/dev/null || true
        cp -r artifacts/* test-artifacts/ 2>/dev/null || true
        cp junit.xml test-artifacts/ 2>/dev/null || true
        cd test-artifacts && zip -r ../test-reports.zip * 
        cd .. && ls -la test-reports.zip
    
    - name: Generate build artifact
      run: |
        mkdir -p build
        cp math.js build/
        cp package.json build/
        echo "Build completed at $(date)" > build/build-info.txt
    
    - name: Upload test reports zip
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-zip
        path: test-reports.zip
        retention-days: 5
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
        retention-days: 5
